# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hun < Formula
  desc "Seamless project context switching for developers"
  homepage "https://hun.sh"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sourabhrathourr/hun/releases/download/v0.1.1/hun_darwin_amd64.tar.gz"
      sha256 "2669e2076d59567690ccb406e8ea6b9fd741ce2471a16226d2151f96d3219aed"

      def install
        bin.install "hun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sourabhrathourr/hun/releases/download/v0.1.1/hun_darwin_arm64.tar.gz"
      sha256 "65614d42b46e359ce749c6f3e463590b93d8570654a9f6d303c8f43cfb4f6d9d"

      def install
        bin.install "hun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourabhrathourr/hun/releases/download/v0.1.1/hun_linux_amd64.tar.gz"
      sha256 "50e048714b70ffaf48e6470e44d9d9c45bde2bbed98c7a78d149276e90ea3f16"
      def install
        bin.install "hun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourabhrathourr/hun/releases/download/v0.1.1/hun_linux_arm64.tar.gz"
      sha256 "4b2eb6810a164007d72f63c0c3fc7831716d8fba2a87701ac53b6438cc300eb9"
      def install
        bin.install "hun"
      end
    end
  end
end
